### ISSUE TITLE
`<pre>` tag should have `white-space: pre`

### ISSUE THREAD

**Issue by nfriedly** [watson-developer-cloud/ui-components#14]
See https://github.com/watson-developer-cloud/ui-components/blob/78a1eeb59bf723b1fd5e715e2d779220c084f1cd/src/scss/lib/vendors/reset/_reset.scss#L270 - it sets `white-space: pre`, but then overrides it (twice), setteling on `white-space: pre-line`, which makes my pretty-printed JSON blocks look ugly.

This gets overridden somewhere for `pre[class*="language-"]` (maybe in the prism css), but I don't see any reason why it shouldn't be the default for other things.

**Comment by nfriedly** [comment]
Oh, and apparently we set `white space: normal` on `.base--pre` somewhere in the CSS - I'm not sure where that comes from...

**Comment by jzhang300** [comment]
I did that to prevent unwanted spacing when we wrap `pre` tags around `code` tags.  `.base--pre code` has `white-space: pre`.

**Comment by germanattanasio** [comment]
Nathan when using react I think if you replace the state of the `Code` component it should reload the new code without you having to change it.

**Comment by nfriedly** [comment]
Something funky is going on. Here's my code:

``` jsx
        return (
            <div className="tab-panels" role="tabpanel">
                <ul className="tab-panels--tab-list" role="tablist">
                    <li className="tab-panels--tab-list-item base--li" role="presentation">
                        <a className="tab-panels--tab base--a active" href="#display_output_doc"
                           aria-controls="display_output_doc" role="tab">Output document</a>
                    </li>
                    <a title="Download output file" href={`/api/convert?document_id=${this.props.id}&conversion_target=${formats[this.props.format]}&download=true`}
                       className="download--output-icon icon icon-download download--icon"></a>
                </ul>
                <div className="tab-panels--tab-content">
                    <div id="display_output_doc" className="tab-panels--tab-pane active" role="tab-panel">
                        <Code type={this.props.format}>{this.state.output}</Code>
                    </div>
                </div>
            </div>
        );
```

And this is what it renders as:

![screen shot 2016-10-05 at 10 06 44 am](https://cloud.githubusercontent.com/assets/114976/19116445/90fafc12-8ae3-11e6-9293-fe85eec601a2.png)

The only CSS I'm including on the page is our `watson-ui-components.min.css`.

If I disable the `white-space: normal` from `.base--pre`, then it looks correct:

![screen shot 2016-10-05 at 10 07 09 am](https://cloud.githubusercontent.com/assets/114976/19116475/a9287396-8ae3-11e6-8c5e-d81ce449f2c3.png)

Should that class maybe be on the `<pre>` tag rather than the `<code>` tag? - That comes from the react components: https://github.com/watson-developer-cloud/react-components/blob/master/src/components/Code.js#L30

**Comment by nfriedly** [comment]
Actually, I think I answered my own question. If I move the `.base--pre`class off of the `<code>` and onto the `<pre>` then things look correct:

![screen shot 2016-10-05 at 10 12 50 am](https://cloud.githubusercontent.com/assets/114976/19116736/7eb8d898-8ae4-11e6-8ae4-90793e3daac0.png)

I included the fix in https://github.com/watson-developer-cloud/react-components/pull/5

**Comment by jzhang300** [comment]
I think in the sample documentation, we should say that `<PrismCode>` needs to be wrapped with `<pre class="base--pre"></pre>`

Edit: nvm, ignore this message
